# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    # - id: no-commit-to-branch
    #   args: ['--branch', 'main']
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files
    - id: detect-private-key
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: mixed-line-ending
      args:
        - "--fix=lf"
    - id: pretty-format-json
      args:
        - "--autofix"
        - "--indent=4"
        - "--no-sort-keys"
  - repo: https://github.com/mattlqx/pre-commit-ruby
    rev: v1.3.5
    hooks:
    - id: rubocop
